SWEP.Base = "nsbase" -- base 
SWEP.PrintName = "M3 Super"
SWEP.Author = "Benelli"
SWEP.Instructions = "Ружье"
SWEP.Category = "Оружие | Дробовики"
SWEP.Spawnable = true
SWEP.AdminOnly = false
------------------------------------------
SWEP.Primary.ClipSize = 8
SWEP.Primary.DefaultClip = SWEP.Primary.ClipSize * 2
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "buckshot"
SWEP.Primary.Cone = 0.06
SWEP.Primary.Damage = 20
SWEP.Primary.Spread = 0
SWEP.Primary.Sound = "weapons/nova/fire.wav"
SWEP.Primary.FarSound = "weapons/nova/distant.wav"
SWEP.Primary.Force = 85
SWEP.ReloadTime = 2.7
SWEP.ShootWait = 0.2
SWEP.NumBullet = 12
SWEP.ReloadSounds = {
    [0.3] = {"weapons/nova/insertshell01.wav"},
    [0.6] = {"weapons/nova/insertshell02.wav"},
    [0.9] = {"weapons/nova/insertshell03.wav"},
    [1.2] = {"weapons/nova/insertshell04.wav"},
    [1.5] = {"weapons/nova/insertshell01.wav"},
    [1.8] = {"weapons/nova/insertshell03.wav"},
    [2.1] = {"weapons/nova/insertshell02.wav"},
    [2.4] = {"weapons/nova/insertshell04.wav"},
    [2.7] = {"weapons/nova/pump.wav"},
}
SWEP.Sight = true
SWEP.TwoHands = true
SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = -1
SWEP.Secondary.Automatic = false
SWEP.Secondary.Ammo = "none"
------------------------------------------
SWEP.Weight = 5
SWEP.AutoSwitchTo = false
SWEP.AutoSwitchFrom = false
SWEP.HoldType = "ar2"
------------------------------------------
SWEP.Slot = 2
SWEP.SlotPos = 2
SWEP.DrawAmmo = true
SWEP.DrawCrosshair = false
SWEP.ViewModel = "models/weapons/nsbase/w_shot_m3super90.mdl"
SWEP.WorldModel = "models/weapons/nsbase/w_shot_m3super90.mdl"
SWEP.addPos = Vector(10, -1.05, 5)
SWEP.addAng = Angle(-10, -0.15, 0)
SWEP.sightPos = Vector(3.7, 7, 0.9)
SWEP.sightAng = Angle(-5, -5, 0)
SWEP.fakeHandRight = Vector(12, -2, 0)
SWEP.fakeHandLeft = Vector(13, -3, -5)
SWEP.Recoil = 2